### ISSUE TITLE
Implementar sistema de edição e exclusão de cobranças

### ISSUE THREAD

**Issue by FelipeCabralz** [FelipeCabralz/financify-frontend#12]

**Comment by jhondutrati** [comment]
Pagina criada, da uma olhada e verifica se precisa de alguma edição

**Comment by jhondutrati** [comment]
feito algumas edições como:
centralização
tamanho
funcionalidade dos botões
rotas definidas

**Comment by jhondutrati** [comment]
pagina atualizada com css
