### ISSUE TITLE
Criação de telas via figma

### ISSUE THREAD

**Issue by jhondutrati** [FelipeCabralz/financify-frontend#13]

**Comment by jhondutrati** [comment]
Segue link do figma com telas para avaliação, aguardo feedback e pontos de melhoria
https://www.figma.com/file/MEpuvoVKyl8QbLWFFa14k7/Wallets-Manager-App?node-id=0-1&t=HFokctlCKS7MTEuk-0

**Comment by jhondutrati** [comment]
Segue atualização, retirada de ícone de foto de todas as telas, permanecendo somente na configuração

**Comment by FelipeCabralz** [comment]
Boa! As telas estão ótimas, se quiser já pode fechar a Issue e ficará como concluida.
